pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/SanthoshSGowda/Website.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                bat '''
                python -m venv venv
                call venv\\Scripts\\activate
                pip install -r requirements.txt
                '''
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                bat '''
                call venv\\Scripts\\activate
                python wsgi.py
                '''
            }
        }
    }
}
